databaseType = "PostgreSql"
id = "c36e9fdf-0453-4294-b187-9d148bc2d4ff"
name = "ROR_db_changes"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
enableMigrations = false

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.nakshaMP]
url = "jdbc:postgresql://10.115.189.77:5432/naksha_mp"
schemas = [ "urban" ]
